#pragma once

#include <stddef.h>

// IANA time zone name -> POSIX TZ string (for tzset()).
//   tzPosixForIana("Australia/Perth")  ->  "AWST-8"
//   tzPosixForIana("Europe/London")    ->  "GMT0BST,M3.5.0/1,M10.5.0"
// Returns nullptr for unknown names.  The table lives in tz_table.cpp, which is
// generated by tools/gen_tz_table.py.
const char *tzPosixForIana(const char *iana);

// The same lookup for a name typed by hand: case does not matter and a space counts as
// an underscore ("australia/perth", "America/New York").  Copies the canonical spelling
// to canonOut (if given) and returns the POSIX rule, or nullptr for an unknown name.
// Scans the whole table, so use it for configuration, not in a loop.
const char *tzFindIanaIgnoreCase(const char *name, char *canonOut, size_t cap);
